import type { Metadata } from "next";
import Image from "next/image";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<div className="min-h-screen grid grid-cols-1 lg:grid-cols-2 items-center justify-center">
			{children}
			<div className="col-span-1 h-screen hidden overflow-hidden lg:block rounded-l-3xl">
                Teste
			</div>
		</div>
	);
}
